create table users (id bigint generated by default as identity, password varchar(255), role varchar(255), user_name varchar(255), primary key (id));
INSERT INTO USERS (password, role, user_name) VALUES ('password', 'admin', 'roshni');
INSERT INTO USERS (password, role, user_name) VALUES ('emp', 'emp', 'roshni1');
